version: '3.5'
services:
  advertisement_postgres:
    image: postgres
    container_name: advertisement_postgres
    env_file:
      - ./src/config/.env.example
    expose:
      - "5432"
    volumes:
      - /advertisement_postgres/data:/var/lib/postgresql/data

  advertisement_service:
    container_name: advertisement_service
    build: ./src/
    env_file:
      - ./src/config/.env.example
    ports:
      - "8000:8000"
